-- Create schedules table
CREATE TABLE IF NOT EXISTS schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    time TEXT NOT NULL,
    room1 TEXT NOT NULL,
    room3 TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE schedules ENABLE ROW LEVEL SECURITY;

-- Create Policy: Allow public read access
CREATE POLICY "Allow public read access" ON schedules
    FOR SELECT USING (true);

-- Insert Data from schedule.json
INSERT INTO schedules (time, room1, room3) VALUES
    ('20:00', '인물 퀴즈', '병뚜껑 컬링'),
    ('20:15', '1초 전주 퀴즈', '절대음감'),
    ('20:30', '몸으로 말해요', '이구동성'),
    ('20:45', '젠가 쌓기', '딱지치기'),
    ('21:00', '인간 스톱워치', '얼굴 포스트잇 떼기');
